### ISSUE TITLE
explode/implode not reversable when using --explodeTrustedCerts

### ISSUE THREAD

**Issue by muemi03** [Layer7-Community/graphman-client#11]
Hi Team.
I am starting to work with the actual graphman-client version 11.1.00
I might be wrong in my understanding.
My expectation: when I export a json bundle ,exploding  it to a directory, 
then  imploding  it again without any changes to the directory content, 
the imploded json bundle should match exactly the original exported bundle again.
That means explode/implode are reversible activities.
Please confirm my above understanding.

The exported certs contains the certBase64 property, their value includes the  windows line breaks (\r\n) every 76 characters.
When I am using the --explodeTrustedCerts option when exploding,
the certBase64 value gets decoded and written into a *.cert file.
Question: What kind of file format is that? How is this file intended to be used?
How could I use this exploded separate cert file, to update a certificate?
When I do the implode again, the generated bundles certBase64 strings do not contain the line-breaks anymore, hence the files differs.
Question: As the certs certBase64 strings obviously already contains the PEM format of the certificate, without the "--begin cert--" and and "--end cert--" lines, wouldn't it be much more useful to generate real certificate files in a valid PEM format?

Thanks for comments and clarifications.
Kind regards
...Michael

**Comment by graju256** [comment]
@muemi03 I think, it is a valid issue with the exploding task. Let me correct this by treating the trustedCert.certBase64 as PEM data for explode.

**Comment by graju256** [comment]
Submitted the PR to fix the issue: https://github.com/Layer7-Community/graphman-client/pull/12

**Comment by muemi03** [comment]
@graju256 . Thanks a million. I incorporated your changes into our version, and it looks fine for me.
