### ISSUE TITLE
request for error message improvement

### ISSUE THREAD

**Issue by muemi03** [Layer7-Community/graphman-client#14]
Dear Team.
This is a request for improving the error message content in the following scenario
source gw: "API 1" : /res1 : goid "123"

once deployed to target gw:
target gw: "API 1" : /res1 : goid "123"

now, on target gw, someone changed "manually" the resolution path to
target gw: "API 1" : /res2 : goid "123"

When doing a deployment of API1 from source to target again, this fails with the following error message:
{
  "errors": [
    {
      "message": "Exception while fetching data (/setWebApiServices) : could not execute statement; SQL [n/a]; constraint [published_service.PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
      "locations": [
        {
          "line": 53,
          "column": 9
        }
      ],
      "path": [
        "setWebApiServices"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {}
}

As to my understanding (based on assumption only), the import fails, because the graphman API tries to create the source API with the given goid, due to the fact that the given resolution path /res1 isn't found in the target.
However the given goid already exists, hence the db complains due to its primary unique index.

If the above assumption is correct, I would expect that the system let me know,, that it tries to **create** the given resource( which one would be helpful as well, especially when importing bundles).
That would lead to a better intuitive understanding what exactly has failed.

Sure, just a thought and a potential improvement.
Thanks
...Michael

**Comment by graju256** [comment]
@muemi03 Agreed. We've addressed this and improved the error reporting by hiding the DB exceptions. Please check it with latest graphman.

FYI, the following error could be observed with the latest graphman if the creation fails for the same reason

```
{
  "data": {
    "setWebApiServices": {
      "detailedStatus": [
        {
          "action": "NEW_OR_UPDATE",
          "status": "ERROR",
          "description": "Error creating or updating SERVICE entity, constraint violation - could not execute statement",
          "source": [
            {
              "name": "resolutionPath",
              "value": "/some-service1"
            }
          ]
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Rolled back the transaction due to errors"
    }
  ]
}
```

**Comment by muemi03** [comment]
Thanks Raju. Great to see this improvement. That fits exactly to my expectations !
