### ISSUE TITLE
v1.2.00 removal of gateway parameters to feed sensitive credential data

### ISSUE THREAD

**Issue by muemi03** [Layer7-Community/graphman-client#39]
Dear Team.

I appreciate the capability to maintain a list of gateways in the GRAPHMAN_HOME/graphman.configuration file.
We've implemented a similar capability in our own wrapper around graphman.sh in the past, feeding the concrete actual current gateway details by the "--sourceGateway. ..." and "--targetGateway. ..." capabilities.
This feeding of gateway parameters is obviously not possible anymore. That means, the sensitive credential information like userid/password needs to be stored in this config file, always,

Especially in regard to automation purposes, where the automation orchestrator (jenkins in our scenario) need access to a lot of gateways including prod systems, I would appreciate to have a more flexible capability again, to feed this sensitive information from the outside, when executing graphman.sh. In such a scenario , the credentials might be visible only at execution time, but not persisted in a file.

Happy to get your thoughts on this. And I hope you get my point.
And yes! This isn't a bug report, but more an enhancement request.

Best regards
...Michael

**Comment by graju256** [comment]
I agree with you in this regard. We will reconsider accepting the credentials via cli parameters. 

Thanks.

**Comment by graju256** [comment]
@muemi03 New client release (v1.3) would make this possible. FYI: https://github.com/Layer7-Community/graphman-client/pull/46

Thanks.
