### ISSUE TITLE
describe issue

### ISSUE THREAD

**Issue by muemi03** [Layer7-Community/graphman-client#40]
Hi Team.

> describe 

love it !!
having a flexible way to call any query which is availble, without the necessity to create queries/*.gql and json file is just geniusly.
Great stuff !
minor issue :

```
graphman.sh describe --query federatedUserByName
[info] query federatedUserByName
[info] excluding the query field FederatedGroup.goid
[info] excluding the query field FederatedGroup.checksum
[info] excluding the query field FederatedGroup.description
[info] excluding the query field FederatedGroup.members
query federatedUserByName($providerName:  String!$name:  String!) {
  federatedUserByName(providerName: $providerNamename: $name) {
    goid
    name
    login
    providerName
    checksum
    subjectDn
    certBase64
    firstName
    lastName
    email
    memberOf {
      name
      providerName
    }
  }
}
```
The two lines are missing the argument/parameter seperator (typically  a comma + space):

query federatedUserByName($providerName:  **String!$name:**  String!) {
  federatedUserByName(providerName: **$providerNamename:** $name) {

might better look like:

query federatedUserByName($providerName:  **String!, $name:**  String!) {
  federatedUserByName(providerName: **$providerName, name:** $name) {

Thanks for this great improvement !!

...Michael

**Comment by graju256** [comment]
Woh, we really appreciate your early feedback. This branch is still under development. I will definitely update you once it is ready to merge.

Thanks, Raju

**Comment by muemi03** [comment]
Yes, of course, I am aware of the dev state.... Sorry for having a preview already. I am just too curious on these things ;)
Thank you
...Michael

**Comment by graju256** [comment]
Fixed the query generation containing multiple arguments. Now, they are comma-separated.

Thanks.

**Comment by muemi03** [comment]
Closing this issue, as it is solved. Thanks a million.
