### ISSUE TITLE
wsdl schema references to other xsd files are not exported

### ISSUE THREAD

**Issue by res13** [Layer7-Community/graphman-client#63]
I noticed that when I export an api gateway config, it does not export the external xsd files that are referenced in a wsdl like so:

```html
<xsd:import schemaLocation="xsds/myXsdExample.xsd" namespace="urn:example.com:enterprise:schemas:reference:currency" />
``` 

This leaves the exported json file in an incomplete state.
In the (old) restman this was working.

**Comment by graju256** [comment]
@res13 I suppose, it is about exporting SOAP services with full WSDL definition.

If yes, we've fixed this functional gap by extending the schema with the v11.1.1 release. Try exporting the soap services by including the below additional fields
 - wsdlUrl
 - wsdlResources {uri content}

For full query, you may use the following **describe** command
```
graphman.sh describe --query serviceByResolutionPath

[info] query serviceByResolutionPath
query serviceByResolutionPath($resolutionPath: String!) {
  serviceByResolutionPath(resolutionPath: $resolutionPath) {
    goid
    guid
    name
    resolutionPath
    resolvers {
      soapActions
      baseUri
      resolutionPath
    }
    serviceType
    checksum
    enabled
    folderPath
    soapVersion
    methodsAllowed
    tracingEnabled
    wssProcessingEnabled
    laxResolution
    properties {
      name
      value
    }
    wsdlUrl
    wsdl
    wsdlResources {
      uri
      content
    }
    policy {
      xml
    }
  }
} 
```

**Comment by res13** [comment]
@graju256 nice thanks. In that case I have one more reason to patch my gateway to the newest release.
/
