### ISSUE TITLE
slice operation enhancement 

### ISSUE THREAD

**Issue by muemi03** [Layer7-Community/graphman-client#69]
I am just looking at the slice capabilities, but started with an example which isn't supported.

gm.sh slice --input diff-report.json --sections inserts

The idea behind is to get easy access to parts of the diff-report results.

Even something like --sections inserts.<section>  might be helpful. 
"insert" is of course just an example for one of "inserts|updates|deletes|diff|mappings", meaning all top-level properties of the diff report.

Once starting to think about, I got the idea of having a slice extension might be beneficial as well, being able to get even more influence on a slice result.

Just  a thought.

 Thanks and regards
...Michael

**Comment by graju256** [comment]
@muemi03 **slice** operation understands bundle sections only. It won't understand any other json documents.

Besides this, are you looking for a control on what to be included in the diff-bundle?
if yes, diff command provides the below options
- --options.includeInserts
- --options.includeUpdates
- --options.includeDeletes

Thanks.

**Comment by muemi03** [comment]
@graju256 
Yes, makes sense. I still don't have the diff --input-report capabilities completely aware in my mind.
You are right I could "slice" the report into inserts only, by using "diff --input-report" and these options.

I am especially interested in getting just the config type resources that will be inserted.
That's the reason I was looking for an extension to do this kind of additional filtering.
Another option would be, that I could do a slice, to only select those resource types I am interested in.
My filtering would be based on resource types that do not own a "policy" property.
I'd like to avoid specifying a list of resource type names as selection criteria.
Understandable? Any idea?

**Comment by graju256** [comment]
@muemi03 

Use slice operation whenever it is needed to filter the bundle at section level (i.e., entity-type level). 
Selection of sections can be done
- either by white-listing where required sections will be listed
- - ex: --sections clusterProperties listenPorts ...
- or by black-listing where not-required sections will be listed with prefix -
- - ex: --sections * -encassConfigs -policies -services

**Comment by muemi03** [comment]
That's great. Black-listing is the thing I was looking for. As you can see, I'm still not aware of all the great new features. :)
Kind regards
... Michael

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by muemi03** [comment]
Closing Issue now, as it's completely answered.
Thank you
