### ISSUE TITLE
Policy As Code - List of assertions used

### ISSUE THREAD

**Issue by OchristianBRC** [Layer7-Community/graphman-client#79]
Hi,
When exporting a large service or multiple services / policies / encass / fragments, it would be nice to have a sort of summary table at the end listing all the assertions that are being used by the policy.
Thanks - Christian

**Comment by burbanski** [comment]
Thanks for the suggestion, @OchristianBRC . We considered adding reporting like this to the graphman-client, but have prioritized related reporting in DCT for now.
