### ISSUE TITLE
Import Dry Run

### ISSUE THREAD

**Issue by OchristianBRC** [Layer7-Community/graphman-client#82]
Hi,
When doing an import to a target gateway, it would be hugely beneficial to have a dry-run capability in oder to verify the impact of changes prior to applying them. This is especially usefull for large bundle files of in situations where you have a lot of dependencies.
Thanks - C

**Comment by muemi03** [comment]
Hi.
Even though an import-dry-run is not yet supported, I think the diff command offers similar data.
Take a look at the diff report. It offers information about what gets inserted, updated and deleted. It even tells you what properties of an entity gets changed.
For me, just excactly I'd need to know before I do the actual import.
Best regard. 
...Michael

**Comment by burbanski** [comment]
Hello, @OchristianBRC. @muemi03 is exactly right. Diff is the right answer for now. If we find that lacking, we can consider additional options in the future.
