### ISSUE TITLE
Cannot import a policy with Validate Schema assertion

### ISSUE THREAD

**Issue by ildarvaliakhmetov** [Layer7-Community/graphman-client#83]
Gateway version: v11.1.1
Graphman client: v1.3.8
Schema v11.1.1

If you export a policy with Validate XML assertion and then tries to import it, then you get an error:

"setPolicies": {
      "detailedStatus": [
        {
          "action": "NEW_OR_UPDATE",
          "status": "ERROR",
          "description": "Error creating or updating POLICY entity, Unable to set the property of the bean com.l7tech.policy.assertion.xml.SchemaValidation.validationTarget",
          "source": [
            {
              "name": "policyType",
              "value": "FRAGMENT"
            },
            {
              "name": "name",
              "value": "policyAsCode"
            }
          ]
        }
      ]
    },

**Comment by ildarvaliakhmetov** [comment]
Fix or any workaround is appreciated.
Best regards, Ildar

**Comment by burbanski** [comment]
Hello, @ildarvaliakhmetov . The preview release of Policy as Code only focused on full support of a handful of assertions. Mileage will vary when importing others. Completing support for Policy as Code is a priority requirement for the new UI project that we're beginning now. That said, it may be some time before that happens. When it does, it will be with core gateway changes that will flow down to the graphman-client. The graphman-client is not directly responsible for the success or failure of Policy as Code.

**Comment by graju256** [comment]
@burbanski 

As of now, we've identified issues with the below assertions
- Validate OData Request
- Validate XML Schema
- Manage Cookie

We've been working on it. Rally tickets are DE615643, DE619577.
